# -*- coding: utf-8 -*-
"""sales_analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yy8zZWjso3idioLEKnTzVgAmjarEi1pN
"""

import pandas as pd
import os
import numpy as np
import kagglehub
from kagglehub import KaggleDatasetAdapter
import gradio as gr
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from pandas.core.frame import DataFrame

"""import kagglehub

# Download latest version
path = kagglehub.dataset_download("pratyushpuri/retail-fashion-boutique-data-sales-analytics-2025")

print("Path to dataset files:", path)
"""

try:
    path = kagglehub.dataset_download("pratyushpuri/retail-fashion-boutique-data-sales-analytics-2025")
    print("Path to dataset files:", path)
except Exception as e:
    print(e)

file_path = ''
#path to downlowad the dataset
download_path = path

#ajustar el directorio
print("Files in downloaded directory:", os.listdir(download_path))

csv_file_name = "fashion_boutique_dataset.csv"
csv_file_path = os.path.join(download_path, csv_file_name)

print("CSV file path:", csv_file_path)

df = pd.read_csv(csv_file_path)
display(df.head())

df.info()

#verificar nulos
df.isnull().sum()

#Eliminar las columnas customer_rating y size con datos nulos

df['size'] = df['size'].fillna('Unknown')

#Verificar
df.isnull().sum()

# Rellenar los valores nulos en 'customer_rating' con la media de la columna
df['customer_rating'] = df['customer_rating'].fillna(df['customer_rating'].mean())

# Rellenar los valores nulos en 'return_reason' con 'Unknown'
df['return_reason'] = df['return_reason'].fillna('Unknown')

# Verificar de nuevo los valores nulos
df.isnull().sum()

display(df.describe())

df['purchase_date'] = pd.to_datetime(df['purchase_date'])

min_purchase_date = df['purchase_date'].min().date()
max_purchase_date = df['purchase_date'].max().date()

print(f"Fecha mínima de compra: {min_purchase_date}")
print(f"Fecha máxima de compra: {max_purchase_date}")

#Asegurar si is_returned es numérica
df['is_returned'] = df['is_returned'].astype(int)
#Categorías únicas
cat_un = sorted(df['category'].unique().tolist())

#Marcas únicas
brand_un = sorted(df['brand'].unique().tolist())

"""#KPI"""

## --- Helper function to create HTML layout for KPIs ---
def gen_htlm_kpi(title, value, color_border='#3B82F6', icon='', background_css='background-color: #ffffff !important;'):
  icon_html = f'<i class="fas {icon} kpi-icon"></i>' if icon else ''
  return f"""
    <div class="kpi-card" style="border-left: 5px solid {color_border}; {background_css}">
    <p class="kpi-title">{icon_html} {title}</p>
    <p class="kpi-value">{value}</p>
    </div>
    """

custom_css = """
  .gradio-container {
    font-family: 'Inter', 'Segoe UI', 'Roboto', 'Helvetica Neue', Arial, sans-serif; /* Improved font stack */
    background: linear-gradient(to bottom, #ffe4e1, #e0ffff); /* Soft pink to light cyan gradient for harmony */
    color: #000000; /* Changed to pure black for clear text */
    box-shadow: 0 8px 25px rgba(0, 0, 0, 0.15); /* More pronounced shadow for the entire dashboard */
  }
  .kpi-card {
    border-radius: 12px;
    box-shadow: 0 4px 8px -2px rgba(0,0,0,0.08); /* Softer shadow for light theme */
    padding: 25px; /* Increased padding */
    margin: 8px; /* Adjusted margin */
    transition: all 0.3s ease-in-out, border-left 0.3s ease-in-out; /* Added border-left to transition */
    /* Removed explicit border to rely on border-left for separation */
    width: 100%; /* Ensure it fills its parent */
    box-sizing: border-box; /* Include padding and border in width */
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    /* background will be set dynamically as a gradient with !important */
  }
  .kpi-card:hover {
    transform:translateY(-3px);
    box-shadow: 0 8px 16px -4px rgba(0,0,0,0.12); /* Lighter shadow on hover */
    border-left: 8px solid var(--kpi-border-hover-color, #3B82F6); /* Thicker border on hover, using a CSS variable */
  }
  .kpi-title {
    color: #000000; /* Changed to pure black for title */
    font-size: 17px; /* Slightly larger for better readability */
    font-weight: 700; /* Bolder font for title */
    text-align: center;
    margin-bottom: 5px;
  }
  .kpi-value {
    color: #000000; /* Changed to pure black for value */
    font-size: 32px; /* Increased size for emphasis */
    font-weight: 900; /* Even bolder font for value */
    text-align: center;
  }
  .kpi-icon {
    margin-right: 8px;
    font-size: 1.5em; /* Adjust size as needed */
    vertical-align: middle;
  }
  /* General Markdown styles for better readability */
  .gradio-markdown h1 {
    font-size: 2.5em;
    color: #000000; /* Changed to pure black */
    text-align: center;
    margin-bottom: 20px;
  }
  .gradio-markdown h3 {
    font-size: 1.5em;
    color: #1a1a1a; /* Darker shade, close to black */
    margin-top: 20px;
    margin-bottom: 10px;
  }
  .gradio-markdown p {
    font-size: 1em;
    line-height: 1.6;
    color: #333333; /* Darker shade for paragraph text */
  }

  .gr-button {
    background-color: transparent; /* Transparent buttons for clean look */
    color: #333333; /* Dark grey text for contrast */
    border-radius: 8px;
    border: 1px solid #dcdcdc; /* Light grey border */
    padding: 10px 20px;
    font-weight: 600;
    box-shadow: 0 2px 4px rgba(0,0,0,0.05);
    transition: all 0.3s ease;
  }
  .gr-button:hover {
    background-color: #e0e0e0; /* Slightly darker grey on hover */
    box-shadow: 0 4px 8px rgba(0,0,0,0.1);
    border-color: #b0b0b0; /* Slightly darker border on hover */
  }

  """
def anal_with_kpis(cat, brad, start_date, end_date):
  # Convert datetime.date to datetime.datetime for comparison
  start_date = pd.to_datetime(start_date)
  end_date = pd.to_datetime(end_date)

  # Filtering the DataFrame is the primary operation that scales with data size.
  # This operation is already vectorized by Pandas for efficiency.
  df_filtered = df[(df['category'] == cat) &
                   (df['brand'] == brad) &
                   (df['purchase_date'] >= start_date) &
                   (df['purchase_date'] <= end_date)].copy()

  if df_filtered.empty:
    empty_fig = px.scatter(title="No data", template="plotly_white", color_discrete_sequence=px.colors.qualitative.Pastel)
    html_error = gen_htlm_kpi("Status", "No Data", "#EF4444", background_css="background-color: #ffffff !important;")
    # Return error KPIs and empty figures for all outputs
    return html_error, html_error, html_error, html_error, html_error, html_error, html_error, empty_fig, empty_fig, empty_fig, empty_fig


  # KPI Gradients and Borders - Updated for even softer colors
  gradient_return_rate_bg = 'linear-gradient(to right, #f2cccc, #e68080)' # Even Softer Red
  border_return_rate = '#e68080'

  gradient_discount_bg = 'linear-gradient(to right, #ffe6cc, #ffbf80)' # Even Softer Gold to Orange
  border_discount = '#ffbf80'

  gradient_inventory_bg = 'linear-gradient(to right, #cce6ff, #80bfff)' # Even Softer Sky Blue to Dodger Blue
  border_inventory = '#80bfff'

  gradient_rating_bg = 'linear-gradient(to right, #e6ccff, #bf80ff)' # Even Softer Violet to Orchid
  border_rating = '#bf80ff'

  gradient_avg_price_bg = 'linear-gradient(to right, #ccffcc, #80ff80)' # Even Softer PaleGreen to LightSeaGreen
  border_avg_price = '#80bfff'

  gradient_sales_volume_bg = 'linear-gradient(to right, #ccffcc, #80ff80)' # Even Softer Chartreuse to LimeGreen
  border_sales_volume = '#80bfff'

  gradient_products_sold_bg = 'linear-gradient(to right, #ffe6f2, #ff80bf)' # Even Softer HotPink to MediumVioletRed
  border_products_sold = '#ff80bf'


  # KPI Calculation
  # Return Rate
  return_rate = df_filtered['is_returned'].mean() * 100
  # Use fixed gradient for return rate
  kpi_dev = gen_htlm_kpi("Return Rate", f"{return_rate:.1f}%", border_return_rate, icon='fa-exchange-alt', background_css=f"background: {gradient_return_rate_bg} !important;")

  # Average Discount
  average_discount = df_filtered['markdown_percentage'].mean()
  kpi_des = gen_htlm_kpi("Avg. Discount", f"{average_discount:.1f}%", border_discount, icon='fa-percent', background_css=f"background: {gradient_discount_bg} !important;")

  # Inventory Value
  inventory_value = df_filtered['current_price'].sum()
  kpi_inv = gen_htlm_kpi("Inventory Value", f"${inventory_value:,.2f}", border_inventory, icon='fa-boxes', background_css=f"background: {gradient_inventory_bg} !important;")

  # Average Rating
  average_rating = df_filtered['customer_rating'].mean()
  rating_str = f"{average_rating:.1f} ★" if not pd.isna(average_rating) else "N/A"
  kpi_rat = gen_htlm_kpi("Customer Rating", rating_str, border_rating, icon='fa-star', background_css=f"background: {gradient_rating_bg} !important;")

  # Average Price
  average_price = df_filtered['current_price'].mean()
  kpi_avg_price = gen_htlm_kpi("Average Price", f"${average_price:,.2f}", border_avg_price, icon='fa-dollar-sign', background_css=f"background: {gradient_avg_price_bg} !important;")

  # Total Sales Volume (new KPI)
  total_sales_volume = df_filtered['current_price'].sum()
  kpi_sales_volume = gen_htlm_kpi("Total Sales Volume", f"${total_sales_volume:,.2f}", border_sales_volume, icon='fa-chart-line', background_css=f"background: {gradient_sales_volume_bg} !important;")

  # Total Products Sold (new KPI)
  total_products_sold = df_filtered['stock_quantity'].sum()
  kpi_products_sold = gen_htlm_kpi("Products Sold", f"{total_products_sold:,.0f}", border_products_sold, icon='fa-shopping-bag', background_css=f"background: {gradient_products_sold_bg} !important;")

  # Interactive Price vs. Discount Chart
  fig = px.scatter (
      df_filtered,
      x="markdown_percentage",
      y="current_price",
      color="color",
      size="stock_quantity",
      hover_data=["customer_rating", "is_returned"],
      title=f"Price vs. Discount for {cat} ({brad})",
      labels={"markdown_percentage": "Discount (%)", "current_price": "Current Price ($)"},
      template="plotly_white",
      color_discrete_sequence=px.colors.qualitative.Pastel # Use a more diverse palette
  )
  fig.update_layout(margin=dict(l=20, r=20, t=50, b=20))

  # New bar chart for Return Reasons (filtered)
  # Filter out 'Unknown' return reasons before counting
  return_reasons_filtered_counts = df_filtered[df_filtered['return_reason'] != 'Unknown']['return_reason'].value_counts().reset_index()
  return_reasons_filtered_counts.columns = ['Return Reason', 'Count']

  fig_returns_filtered = px.bar(
      return_reasons_filtered_counts,
      x='Return Reason',
      y='Count',
      title=f'Return Reasons Frequency for {cat} ({brad}) (Excluding "Unknown")',
      labels={'Return Reason': 'Return Reason', 'Count': 'Count'},
      color_discrete_sequence=px.colors.qualitative.Pastel, # Diverse palette
      template='plotly_white'
  )
  fig_returns_filtered.update_layout(margin=dict(l=20, r=20, t=50, b=20))

  # New scatter plot for Price vs. Rating
  fig_price_rating = px.scatter(
      df_filtered,
      x="customer_rating",
      y="current_price",
      color="season",
      size="stock_quantity",
      hover_data=["product_id", "brand"],
      title=f"Price vs. Customer Rating for {cat} ({brad})",
      labels={"customer_rating": "Customer Rating", "current_price": "Current Price ($)"},
      template="plotly_white",
      color_discrete_sequence=px.colors.qualitative.Pastel # Diverse palette
  )
  fig_price_rating.update_layout(margin=dict(l=20, r=20, t=50, b=20))

  # New scatter plot for Stock vs. Rating
  fig_stock_rating = px.scatter(
      df_filtered,
      x="stock_quantity",
      y="customer_rating",
      color="season",
      size="current_price",
      hover_data=["product_id", "brand"],
      title=f"Stock vs. Customer Rating for {cat} ({brad})",
      labels={"stock_quantity": "Stock Quantity", "customer_rating": "Customer Rating"},
      template="plotly_white",
      color_discrete_sequence=px.colors.qualitative.Pastel # Diverse palette
  )
  fig_stock_rating.update_layout(margin=dict(l=20, r=20, t=50, b=20))

  return kpi_dev, kpi_des, kpi_inv, kpi_rat, kpi_avg_price, kpi_sales_volume, kpi_products_sold, fig, fig_returns_filtered, fig_price_rating, fig_stock_rating

"""#Diseño interfaz"""

with gr.Blocks() as demo:
  gr.HTML('<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">')
  gr.Markdown("# &#8505; Corporate Sales Dashboard (Fashion Retail 2025)")
  gr.Markdown("Filter by category and brand to audit key KPIs and pricing strategy in real-time.")

  with gr.Row():
    with gr.Column(scale=1):
      gr.Markdown("### &#128197; Selection Filters")
      input_cat = gr.Dropdown(choices=cat_un, value=cat_un[5], label="Product Category")
      input_marca = gr.Dropdown(choices=brand_un, value=brand_un[6], label="Brand")

      # Replaced gr.Date with gr.Textbox as a workaround
      input_start_date = gr.Textbox(value=str(min_purchase_date), label="Start Date (YYYY-MM-DD)")
      input_end_date = gr.Textbox(value=str(max_purchase_date), label="End Date (YYYY-MM-DD)")

      # New button and file component for report download
      report_button = gr.Button("Download Report")
      report_file = gr.File(label="Downloadable Report", file_count="single", interactive=False)

      # New button for refresh (moved to the bottom of the filter section)
      refresh_button = gr.Button("Refresh Data")

    with gr.Column(scale=3):
      gr.Markdown("### &#128202; Key Performance Indicators (KPIs)")
      # Fila horizontal para las 3 primeras tarjetas de KPI
      with gr.Row():
        with gr.Column(scale=1):
          out_kpi_dev = gr.HTML()
        with gr.Column(scale=1):
          out_kpi_desc = gr.HTML()
        with gr.Column(scale=1):
          out_kpi_inv = gr.HTML()
      # Nueva fila horizontal para las 3 siguientes tarjetas de KPI
      with gr.Row():
        with gr.Column(scale=1):
          out_kpi_rate = gr.HTML()
        with gr.Column(scale=1):
          out_kpi_avg_price = gr.HTML()
        with gr.Column(scale=2): # This KPI will be wider
          out_kpi_sales_volume = gr.HTML() # New KPI output
        with gr.Column(scale=1):
          out_kpi_products_sold = gr.HTML() # New KPI output for total products sold

  with gr.Row():
    with gr.Column():
      gr.Markdown("### &#128202; Inventory and Pricing Analysis")
      out_grafico = gr.Plot()
    with gr.Column(): # New column for return reasons chart
      gr.Markdown("### &#128202; Return Reasons")
      out_returns_chart = gr.Plot()

  with gr.Row():
    with gr.Column():
      gr.Markdown("### &#128202; Average Rating by Category")
      out_avg_rating_chart = gr.Plot()
    with gr.Column():
      gr.Markdown("### &#128202; Price vs. Customer Rating Relationship")
      out_price_rating_chart = gr.Plot()

  with gr.Row(): # New row for conversion rate chart
    with gr.Column():
      gr.Markdown("### &#128202; Average Conversion Rate by Category")
      out_conversion_rate_chart = gr.Plot()
    with gr.Column(): # New column for monthly sales trend chart
      gr.Markdown("### &#128202; Monthly Sales Trend")
      out_monthly_sales_chart = gr.Plot()

  with gr.Row(): # New row for the average price by brand chart
    with gr.Column():
      gr.Markdown("### &#36; &#128202; Average Price by Brand")
      out_avg_price_by_brand_chart = gr.Plot()

  with gr.Row(): # New row for Stock vs. Rating chart
    with gr.Column():
      gr.Markdown("### &#128202; Stock vs. Customer Rating")
      out_stock_rating_chart = gr.Plot()

  # Function to generate and download report
  def download_report(cat, brand, start_date, end_date):
    # Ensure dates are parsed correctly from Textbox components for filtering
    start_date = pd.to_datetime(start_date)
    end_date = pd.to_datetime(end_date)
    df_filtered = df[(df['category'] == cat) &
                     (df['brand'] == brand) &
                     (df['purchase_date'] >= start_date) &
                     (df['purchase_date'] <= end_date)]

    if df_filtered.empty:
      return None
    # Save to a temporary CSV file
    temp_file = "filtered_report.csv"
    df_filtered.to_csv(temp_file, index=False)
    return temp_file

  # Reactividad automática
  inputs_lista = [input_cat, input_marca, input_start_date, input_end_date]
  outputs_lista = [
      out_kpi_dev, out_kpi_desc, out_kpi_inv, out_kpi_rate, out_kpi_avg_price,
      out_kpi_sales_volume, out_kpi_products_sold, # Add new KPI output here
      out_grafico, out_returns_chart, out_price_rating_chart, out_stock_rating_chart # Add new chart output here
  ]

  input_cat.change(fn=anal_with_kpis, inputs=inputs_lista, outputs=outputs_lista)
  input_marca.change(fn=anal_with_kpis, inputs=inputs_lista, outputs=outputs_lista)
  input_start_date.change(fn=anal_with_kpis, inputs=inputs_lista, outputs=outputs_lista)
  input_end_date.change(fn=anal_with_kpis, inputs=inputs_lista, outputs=outputs_lista)
  demo.load(fn=anal_with_kpis, inputs=inputs_lista, outputs=outputs_lista)

  # Link the refresh button to update dynamic data
  refresh_button.click(fn=anal_with_kpis, inputs=inputs_lista, outputs=outputs_lista)

  # Logic for the new static chart (avg rating by category)
  avg_rating_by_category = df.groupby('category')['customer_rating'].mean().reset_index()
  fig_avg_rating = px.bar(
      avg_rating_by_category,
      x='category',
      y='customer_rating',
      title='Average Rating by Category',
      labels={'category': 'Product Category', 'customer_rating': 'Average Rating'},
      color_discrete_sequence=px.colors.qualitative.Pastel, # Diverse palette
      template='plotly_white'
  )
  fig_avg_rating.update_layout(margin=dict(l=20, r=20, t=50, b=20))
  # Load the static average rating chart once
  demo.load(fn=lambda: fig_avg_rating, inputs=None, outputs=out_avg_rating_chart, queue=False)

  # Logic for Average Conversion Rate by Category
  # Assuming 'conversion' means not returned (is_returned == 0)
  conversion_rate_by_category = df.groupby('category')['is_returned'].apply(lambda x: (x == 0).mean()).reset_index()
  conversion_rate_by_category.columns = ['Category', 'Conversion_Rate']
  conversion_rate_by_category['Conversion_Rate'] = conversion_rate_by_category['Conversion_Rate'] * 100 # Convert to percentage

  fig_conversion_rate = px.bar(
      conversion_rate_by_category,
      x='Category',
      y='Conversion_Rate',
      title='Average Conversion Rate by Category',
      labels={'Category': 'Product Category', 'Conversion_Rate': 'Conversion Rate (%)'},
      color_discrete_sequence=px.colors.qualitative.Pastel, # Diverse palette
      template='plotly_white'
  )
  fig_conversion_rate.update_layout(margin=dict(l=20, r=20, t=50, b=20))
  # Load the static conversion rate chart once
  demo.load(fn=lambda: fig_conversion_rate, inputs=None, outputs=out_conversion_rate_chart, queue=False)

  # Logic for Monthly Sales Trend Chart
  # Ensure purchase_date is datetime for this calculation
  df['purchase_date'] = pd.to_datetime(df['purchase_date'])
  monthly_sales = df.groupby(df['purchase_date'].dt.to_period('M'))['current_price'].sum().reset_index()
  monthly_sales['purchase_date'] = monthly_sales['purchase_date'].astype(str)

  fig_monthly_sales = px.line(
      monthly_sales,
      x='purchase_date',
      y='current_price',
      title='Monthly Sales Trend',
      labels={'purchase_date': 'Month', 'current_price': 'Total Sales ($)'},
      color_discrete_sequence=px.colors.qualitative.Pastel, # Diverse palette
      template='plotly_white'
  )
  fig_monthly_sales.update_layout(margin=dict(l=20, r=20, t=50, b=20))
  # Load the static monthly sales chart once
  demo.load(fn=lambda: fig_monthly_sales, inputs=None, outputs=out_monthly_sales_chart, queue=False)

  # Logic for Average Price by Brand Chart (moved inside Blocks context)
  avg_price_by_brand = df.groupby('brand')['current_price'].mean().reset_index()
  fig_avg_price_by_brand = px.bar(
      avg_price_by_brand,
      x='brand',
      y='current_price',
      title='Average Price by Brand',
      labels={'brand': 'Brand', 'current_price': 'Average Price ($)'},
      color_discrete_sequence=px.colors.qualitative.Pastel, # Diverse palette
      template='plotly_white'
  )
  fig_avg_price_by_brand.update_layout(margin=dict(l=20, r=20, t=50, b=20))
  # Load the static average price by brand chart once
  demo.load(fn=lambda: fig_avg_price_by_brand, inputs=None, outputs=out_avg_price_by_brand_chart, queue=False)

  # Link report button to download function
  report_button.click(
      fn=download_report,
      inputs=[input_cat, input_marca, input_start_date, input_end_date],
      outputs=report_file
  )

demo.launch(share=True, css=custom_css)



correlation = df['stock_quantity'].corr(df['customer_rating'])
print(f"El coeficiente de correlación de Pearson entre Stock Quantity y Customer Rating es: {correlation:.4f}")

if correlation > 0.7:
    print("Hay una fuerte correlación positiva: a mayor stock, mayor rating de cliente.")
elif correlation < -0.7:
    print("Hay una fuerte correlación negativa: a mayor stock, menor rating de cliente.")
elif abs(correlation) >= 0.3:
    print("Hay una correlación moderada entre stock y rating de cliente.")
else:
    print("Hay una correlación débil o nula entre stock y rating de cliente.")